trigger:
- master

pool:
  vmImage: ubuntu-latest
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--configuration Release --no-build --no-restore'
    testRunTitle: 'azure-pipelines'

